apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "cluster-logging"
  namespace: "openshift-logging" 
spec:
  channel: "preview"
  installPlanApproval: "Automatic"
  source: "cluster-logging"
  sourceNamespace: "openshift-logging" 
  name: "cluster-logging"
